apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: albertdevopstrain
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: albertdevopstrain
    spec:
      containers:
      - name: albertdevopstrain
        image: docker.io/pleungdev/albertdevopstrain:$BUILD_ID
        ports:
        - containerPort: 16731
---
apiVersion: v1
kind: Service
metadata:
  name: albertdevopstrain
spec:
  type: LoadBalancer
  ports:
  - port: 16731
  selector:
    app: albertdevopstrain
